# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecettesMamieMone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecettesMamieMone
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/RemoteConfig'
  pod 'SDWebImage'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'RecettesMamieMoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
